name: sample

on:
  push:
    branches:
      - main 
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "build completed"
        

  Compile:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
  Deploy:  
    name: 'ServiceNow DevOps Change Automation'
    runs-on: ubuntu-latest
    needs: Compile
    steps:
      - name: ServiceNow DevOps Change Automation1
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        with:
            devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            context-github: ${{ toJSON(github) }}
            job-name: 'ServiceNow DevOps Change Automation'
            change-request:  '{"attributes": { "chg_model":{"name": "DevOps"},"start_date": "2025-09-04 13:10:00","end_date": "2025-09-04 13:20:00" }}'
            interval: '100'
            timeout: '3600'
            changeCreationTimeOut: '3600'
            abortOnChangeCreationFailure: true
            abortOnChangeStepTimeout: true
     
