name: sample

on:
  push:
    branches:
      - main 
      - develop
  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        run: echo "build completed"
        

  Compile:
    runs-on: ubuntu-latest 
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
  Deploy:  
    name: ServiceNow DevOps Change Automation
    runs-on: ubuntu-latest
    needs: Compile
    steps:
      - name: ServiceNow DevOps Change Automation1
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        with:
            devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            context-github: ${{ toJSON(github) }}
            job-name: 'ServiceNow DevOps Change Automation'
         # Use  change-request:  '{"attributes": { "chg_model":{"name": "DevOps"},"start_date": "2025-09-04 13:10:00","end_date": "2025-09-04 13:20:00" }}'
         #   change-request:  '{"attributes":{"u_source_refid": "TESTAPI_mmddyyhhmm","u_source": "TEST API","u_affected_ci": "ServiceNow Development","u_assignment_group": "ServiceNow implementation Team","u_type": "normal","u_category": "Applications Software","requested_by": {"name": "Devika Shukla"},"u_requested_by_email": "Devika.Shukla@travelport.com","u_requested_by_id": "739912","u_environment": "pp","u_short_description": "Automated Software Deployment",                "u_description": "Automated Software Deployment","u_justification": "Automated Software Deployment Test with Service NOw DevOps","u_implementation_plan": "Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window","u_test_plan": "Testing if the software was successfully deployed","u_backout_plan": "When software fails in production, the previous software release will be re-deployed","u_scheduled_start_date": "2025-01-13 06:00:00","u_scheduled_end_date": "2025-01-13 06:30:00","u_customer_facing": "no","u_delta_created": "","u_impact": "1","u_priority": "2","u_resiliency_testing": "","u_risk": "2","u_complex_change": "no","u_impact_duration": "yes","u_system_app_network_down": "yes","u_planned_impact": "yes","u_fallback_duration": "10 Min","u_mandate_governance_pci": "yes"}}'
            change-request:
             '{"attributes":{"u_source_refid": "TESTAPI_mmddyyhhmm","u_source": "TEST API","u_affected_ci": "ServiceNow Development","u_assignment_group": "ServiceNow implementation Team","u_type": "normal","u_category": "Applications Software","requested_by": {"name": "Devika Shukla"},"u_requested_by_email": "Devika.Shukla@travelport.com","u_requested_by_id": "739912","u_environment": "pp","u_short_description": "Automated Software Deployment",                "u_description": "Automated Software Deployment","u_justification": "Automated Software Deployment Test with Service NOw DevOps","u_implementation_plan": "Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window","u_test_plan": "Testing if the software was successfully deployed","u_backout_plan": "When software fails in production, the previous software release will be re-deployed","u_scheduled_start_date": "2025-01-13 06:00:00","u_scheduled_end_date": "2025-01-13 06:30:00","u_customer_facing": "no","u_delta_created": "","u_impact": "1","u_priority": "2","u_resiliency_testing": "","u_risk": "2","u_complex_change": "no","u_impact_duration": "yes","u_system_app_network_down": "yes","u_planned_impact": "yes","u_fallback_duration": "10 Min","u_mandate_governance_pci": "yes"}}'
            interval: '100'
            timeout: '3600' 
            changeCreationTimeOut: '3600'
            abortOnChangeCreationFailure: true
            abortOnChangeStepTimeout: true
     
